RNA Seq
CSBiology/BioFSharp pull request #136
Opened 2024-05-06 06:26 UTC by ScheidTo

Thank you for contributing to BioFSharp. Please take the time to tell us a bit more about your PR.

**Please list the changes introduced in this PR**

- added RPKM Normalization 
- added TPM Normalization

**Description**
This contribution adds RPKM and TPM normalization, as well as unit tests and documentation. RPKM and TPM are metrics for normalized RNA-sequencing data.

**[Required]** please make sure you checked that
 - [x] The project builds without problems on your machine

**[Optional]**
 - [x] Added unit tests regarding the added features

2024-05-06 08:36 UTC, kMutagene commented on src/BioFSharp.Stats/RNASeq.fs
> +module RNASeq =
At least the public functions and types in this module should have XML documentation.

2024-05-06 08:46 UTC, kMutagene requested changes
Looks good so far. The documentation page could use some more information, see the individual comments. Here are some relevant sources:
- [a reference notebook that uses latex to render formulas]()
- [supported latex reference](https://katex.org/docs/supported.html)
- [xml documentation](https://learn.microsoft.com/en-us/dotnet/fsharp/language-reference/xml-documentation#comments-with-xml-tags)

2024-05-06 08:46 UTC, kMutagene commented on tests/BioFSharp.Tests/BioFSharp.Stats/RNASeqTests.fs
> +                |> Array.ofSeq)
You can use `Expect.sequenceEqual` here instead of casting to arrays.

2024-05-06 08:46 UTC, kMutagene commented on src/BioFSharp.Stats/RNASeq.fs
> +module RNASeq =
At least the public functions and types in this module should have XML documentation.

2024-05-06 13:04 UTC, ScheidTo commented
@kMutagene

2024-05-13 07:01 UTC, kMutagene requested changes
Nice!

small nitpick and we can merge this: 

the y axis titles on the plot should be different from each other, as they are not all indicate 'Read Counts'. For that, you can set the axis title on the individual charts before creating the grid. Also, a little more space to improve readability and keep axes from overlapping would be nice (see `Chart.withSize`)

2024-05-13 10:54 UTC, kMutagene approved these changes

2024-05-13 10:54 UTC, kMutagene commented
🥳

2024-05-14 06:26 UTC, merged